
'use strict';

var patterns = [
    {
        // Lỗi điều kiện
        "regex": /\s(.+)=\1+/,
        "description": "Equality expression. (ex. 1=1)"
    },
    {
        // Lỗi chứa từ khóa trong SQL
        "regex": /\s(SELECT|DROP|UPDATE|CREATE|INSERT|ALTER|UNION|MERGE|LIKE|GROUP BY|ORDER BY|ADD|ADD CONSTRAINT|ALL|ALTER COLUMN|ALTER TABLE|AND|ANY|AS|ASC|BETWEEN|CASE|CHECK|COLUMN|CONSTRAINT|CREATE DATABASE|CREATE INDEX|CREATE OR REPLACE VIEW|CREATE TABLE|CREATE PROCEDURE|CREATE UNIQUE INDEX|CREATE VIEW|DATABASE|DEFAULT|DELETE|DESC|DISTINCT|DROP COLUMN|DROP CONSTRAINT|DROP DATABASE|DROP DEFAULT|DROP INDEX|DROP TABLE|DROP VIEW|EXEC|EXISTS|FOREIGN KEY|FROM|FULL OUTER JOIN|HAVING|IN|INDEX|INNER JOIN|INSERT INTO|INSERT INTO SELECT|IS NULL|IS NOT NULL|JOIN|LEFT JOIN|LIMIT|NOT|NOT NULL|OR|OUTER JOIN|PRIMARY KEY|PROCEDURE|RIGHT JOIN|ROWNUM|SELECT DISTINCT|SELECT INTO|SELECT TOP|SET|TABLE|TOP|TRUNCATE TABLE|UNION ALL|UNIQUE|VALUES|VIEW|WHERE|SHUTDOWN|SLEEP)/i,
        "description": "SQL query keyword. (ex. DROP)"
    },
    {
        // Các hàm xử lý chuỗi trong MySQL
        "regex": /\s(ASCII|CHAR_LENGTH|CHARACTER_LENGTH|CONCAT|CONCAT_WS|FIELD|FIND_IN_SET|FORMAT|INSTR|LCASE|LEFT|LENGTH|LOCATE|LOWER|LPAD|LTRIM|MID|POSITION|REPEAT|REPLACE|REVERSE|RIGHT|RPAD|RTRIM|SPACE|STRCMP|SUBSTR|SUBSTRING|SUBSTRING_INDEX|TRIM|UCASE|UPPER)/i,
        "description": "SQL query keyword. (ex. DROP)"
    },
    {
        // Các hàm xử lý số trong MySQL
        "regex": /\s(ABS|ACOS|ASIN|ATAN|ATAN2|AVG|CEIL|CEILING|COS|COT|COUNT|DEGREES|DIV|EXP|FLOOR|GREATEST|LEAST|LN|LOG|LOG10|LOG2|MAX|MIN|MOD|PI|POW|POWER|RADIANS|RAND|ROUND|SIGN|SIN|SQRT|SUM|TAN|TRUNCATE)/i,
        "description": "SQL query keyword. (ex. DROP)"
    },
    {
        // Các hàm xử lý ngày trong MySQL
        "regex": /\s(ADDDATE|ADDTIME|CURDATE|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURTIME|DATE|DATEDIFF|DATE_ADD|DATE_FORMAT|DATE_SUB|DAY|DAYNAME|DAYOFMONTH|DAYOFWEEK|DAYOFYEAR|EXTRACT|FROM_DAYS|HOUR|LAST_DAY|LOCALTIME|LOCALTIMESTAMP|MAKEDATE|MAKETIME|MICROSECOND|MINUTE|MONTH|MONTHNAME|NOW|PERIOD_ADD|PERIOD_DIFF|QUARTER|SECOND|SEC_TO_TIME|STR_TO_DATE|SUBDATE|SUBTIME|SYSDATE|TIME|TIME_FORMAT|TIME_TO_SEC|TIMEDIFF|TIMESTAMP|TO_DAYS|WEEK|WEEKDAY|WEEKOFYEAR|YEAR|YEARWEEK)/i,
        "description": "SQL query keyword. (ex. DROP)"
    },
    {
        // Các hàm nâng cao trong MySQL
        "regex": /\s(BIN|BINARY|CASE|CAST|COALESCE|CONNECTION_ID|CONV|CONVERT|CURRENT_USER|DATABASE|IF|IFNULL|ISNULL|LAST_INSERT_ID|NULLIF|SESSION_USER|SYSTEM_USER|USER|VERSION)/i,
        "description": "SQL query keyword. (ex. DROP)"
    },
    {   // Lỗi chứa hàm SQL liên quan đến tên người dùng, tên database, tên server, ...
        "regex": /(CURRENT_USER|CURRENT_USER\(\)|USER\(\)|BACKUP DATABASE)/i,
        "description": "SQL function. (ex. CURRENT_USER())"
    },
    {
        "regex": /(USER)/,
        "description": "MS SQL function. (ex. USER)"
    },
    {
        // Lỗi các ký tự đặc biệt
        "regex": /'(''|[^'])*'/,
        "description": "SQL Statements"
    },
];

module.exports = patterns;